"""initial_migration

Revision ID: 6e20f64b2ab7
Revises: 
Create Date: 2026-07-16 13:04:51.344275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e20f64b2ab7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('retail_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('payment_method', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('preparation', sa.BigInteger(), nullable=True),
    sa.Column('count_type', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('weight_with_packaging', sa.Integer(), nullable=True),
    sa.Column('payk_delivery', sa.SmallInteger(), nullable=True),
    sa.Column('post_delivery', sa.SmallInteger(), nullable=True),
    sa.Column('coverage_area', sa.SmallInteger(), nullable=True),
    sa.Column('image_1', sa.String(length=500), nullable=True),
    sa.Column('image_2', sa.String(length=500), nullable=True),
    sa.Column('image_3', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retail_products_id'), 'retail_products', ['id'], unique=False)
    op.create_index(op.f('ix_retail_products_retail_id'), 'retail_products', ['retail_id'], unique=False)
    op.create_index(op.f('ix_retail_products_session_id'), 'retail_products', ['session_id'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('retail_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1500), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('client_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('count_action', sa.Integer(), nullable=True),
    sa.Column('count_failed_action', sa.Integer(), nullable=True),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_model', sa.String(length=255), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=True),
    sa.Column('ai_costs', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_id'), 'user_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_user_interactions_retail_id'), 'user_interactions', ['retail_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_session_id'), 'user_interactions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_interactions_session_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_retail_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_retail_products_session_id'), table_name='retail_products')
    op.drop_index(op.f('ix_retail_products_retail_id'), table_name='retail_products')
    op.drop_index(op.f('ix_retail_products_id'), table_name='retail_products')
    op.drop_table('retail_products')
    # ### end Alembic commands ###
